import { useEffect, useState } from 'react';
import { X, FileText, Download, Layers3, Users, Map, ArrowUpRight, Landmark, Info, ChevronDown, Search, Mouse, Move, Rotate3D, Scroll } from 'lucide-react';
import type { Building, Finding, ModalKind, Unit, RecordContext } from '../types';
import { useDialog } from './useDialog';
import RegisterOverview from './RegisterOverview';
import { district } from '../data/district';
import { documentFields, documentTitles, downloadDocument, money } from '../data/documents';
import type { DocumentType } from '../data/documents';
import { BuildingPreview, FloorPlan, AerialMap } from './Visuals';
import './inspection.css';
type Props={kind:ModalKind;building:Building;findings:Finding[];onClose:()=>void;onFloor:(f:number|null)=>void;context?:RecordContext;preview?:string};
export default function RecordModal({kind,building:b,findings,onClose,onFloor,context={},preview}:Props){
  const initialUnit=b.units.find(u=>u.id===context.unitId)||b.units.find(u=>u.floor===context.floor)||b.units.find(u=>u.tenure==='Rented')||b.units[0];
  const [docType,setDocType]=useState<DocumentType>(context.doc||(context.unitId?'lease':'land')),[unit,setUnit]=useState<Unit>(initialUnit),[floor,setFloor]=useState(context.floor??initialUnit.floor),[showDoc,setShowDoc]=useState(kind==='documents'||Boolean(context.unitId));
  const dialogRef=useDialog(onClose);

  const title=kind==='register'?'Building register':kind==='aerial'?'District aerial overview':kind==='help'?'Explore the district':'Evidence & documents';
  const openDocument=(type:DocumentType,u?:Unit)=>{setDocType(type);if(u){setUnit(u);setFloor(u.floor);}setShowDoc(true);};
  return <div className={`rec-backdrop ${kind==='register'?'register-workspace':''}`} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="record-title" className={`rec-modal ${kind==='aerial'?'rec-aerial-modal':''}`}>
    <header className="rec-header"><div><span className="rec-header-icon">{kind==='aerial'?<Map size={21}/>:<FileText size={21}/>}</span><div><h2 id="record-title">{title}</h2><p>{b.ulpin} <span> / </span> {b.name}</p></div></div><div><span className="demo-label">SYNTHETIC DEMO</span>{kind==='register'&&<button className="back-to-map" onClick={onClose}>Back to map <ArrowUpRight size={14}/></button>}<button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={22}/></button></div></header>
    <div className="rec-body">
      {kind==='help'?<div className="rec-help"><h2>A whole neighbourhood, connected.</h2><p>Explore {district.buildings.length} buildings, their parcels, floors, residents and inspection evidence. No map API key or server database is required.</p><div className="rec-help-grid">{[[Move,'Pan','Drag with the left mouse button.'],[Rotate3D,'Orbit & tilt','Drag with the right mouse button.'],[Mouse,'Zoom','Scroll in and out, or use + / −.'],[Search,'Find a property','Search its 14-digit demo ULPIN, owner or address.'],[Layers3,'Inspect floors','Select a building, then choose Floors or Explode.'],[Map,'See the entire area','Use Fit district. Click the minimap to jump to a building.']].map(([Icon,t,d])=>{const I=Icon as typeof Move;return <div key={String(t)}><I size={23}/><h3>{String(t)}</h3><p>{String(d)}</p></div>;})}</div><div className="rec-disclaimer"><Info size={18}/><p>Buildings, parcels, identifiers, residents and documents are generated fixtures, not official or surveyed records. The visual style follows the supplied mockups; this is not photogrammetry. Underground pipe sizes are exaggerated for visibility; elevation values remain in local metres.</p></div></div>:
      kind==='aerial'?<div className="rec-aerial-layout"><div className="rec-aerial-map"><AerialMap selected={b.id}/></div><aside><span className="ins-eyebrow">ORTHOGRAPHIC DISTRICT SHEET</span><h2>Lake View District</h2><p>The complete district, generated from the same parcel and building geometry as the 3D map.</p><div className="rec-aerial-stats"><strong>{district.buildings.length}<small>Buildings</small></strong><strong>0.69<small>km² local extent</small></strong><strong>{district.parks.length}<small>Public parks</small></strong></div><p className="rec-legend"><i style={{background:'#dc745b'}}/>Selected building<br/><i style={{background:'#efe6d2'}}/>Modelled buildings<br/><i style={{background:'#88a16b'}}/>Public land<br/><i style={{background:'#7e8980'}}/>Road corridors</p><button className="primary-button" onClick={()=>downloadDocument('aerial',b)}><Download size={16}/>Download overview PDF</button><div className="rec-disclaimer"><Info size={17}/><p>This is a synthetic aerial-style diagram, not a drone or satellite photograph. North is at the top; local extent is 832 × 832 m.</p></div></aside></div>:
      <div className="rec-layout"><aside className="rec-property">{preview?<img className="building-preview" src={preview} alt={b.name}/>:<BuildingPreview b={b}/>}<h3>{b.name}</h3><code>{b.ulpin}</code><p>{b.address}</p><div className="rec-property-stats"><span>{b.floors}<small>Floors</small></span><span>{b.units.length}<small>Units</small></span><span>{b.height.toFixed(1)}<small>Height, m</small></span></div><div className="rec-owner"><Landmark size={17}/><div><small>Recorded owner · fictional</small><strong>{b.owner}</strong></div></div><button onClick={()=>{setShowDoc(false);}} className={!showDoc&&kind==='register'?'active':''}><Layers3 size={15}/>Floor & occupancy schedule</button><button onClick={()=>openDocument('land')}><Landmark size={15}/>Land & parcel record</button><button onClick={()=>openDocument('plan')}><Map size={15}/>Illustrative floor plan</button><button onClick={()=>openDocument('lease')}><Users size={15}/>Occupancy agreement</button><button onClick={()=>downloadDocument('register',b)}><Download size={15}/>Download complete register</button><div className="ins-note">All linked people and evidence are fictional. Documents carry a visible demo disclaimer.</div></aside>
      <main className="rec-main">
        {!showDoc?<RegisterOverview b={b} unit={unit} floor={floor} onFloor={f=>{setFloor(f);setUnit(old=>old.floor===f?old:(b.units.find(u=>u.floor===f)||old));}} onUnit={u=>{setUnit(u);setFloor(u.floor);}} onDocument={u=>openDocument('lease',u)} onMap={f=>{onFloor(f);onClose();}}/>:<>

          <div className="rec-doc-tabs">{(['land','plan','lease'] as DocumentType[]).map(t=><button key={t} onClick={()=>setDocType(t)} className={docType===t?'active':''}>{t==='land'?'Land record':t==='plan'?'Floor plan':'Occupancy record'}</button>)}</div>
          <div className="rec-section-heading"><div><span className="ins-eyebrow">INSPECTION SPECIMEN</span><h2>{documentTitles[docType]}</h2></div><button className="primary-button" onClick={()=>downloadDocument(docType,b,unit,floor)}><Download size={15}/>PDF</button></div>
          {docType==='plan'&&<div className="rec-doc-control"><label>Floor<select aria-label="Floor" value={floor} onChange={e=>setFloor(Number(e.target.value))}>{Array.from({length:b.floors},(_,f)=><option key={f} value={f}>{f===0?'Ground floor':`Floor ${f}`}</option>)}</select></label></div>}
          {docType==='lease'&&<div className="rec-doc-control"><label>Unit / occupant<select aria-label="Unit and occupant" value={unit.id} onChange={e=>{const u=b.units.find(u=>u.id===e.target.value)!;setUnit(u);setFloor(u.floor);}}>{b.units.map(u=><option key={u.id} value={u.id}>Unit {u.number} · {u.occupant}</option>)}</select></label></div>}
          <div className="rec-document"><div className="rec-paper-brand">3D ULPIN <span>INSPECTION COPY</span></div><h3>{documentTitles[docType]}</h3><div className="rec-paper-warning">SYNTHETIC DEMO · NOT A LEGAL OR GOVERNMENT RECORD</div>{docType==='plan'&&<FloorPlan b={b} floor={floor} selectedUnit={unit.id} onUnit={id=>{const found=b.units.find(u=>u.id===id);if(found){setUnit(found);setFloor(found.floor);setDocType('lease');}}}/>}<dl className="rec-doc-fields">{documentFields(docType,b,unit,floor).map(([l,v])=><div key={l}><dt>{l}</dt><dd>{v}</dd></div>)}</dl><p className="rec-paper-note">This specimen demonstrates linked property information only. It contains no real personal records, signatures, issued ULPINs, sanctioned drawings or legally valid agreements.</p></div>
        </>}
      </main>{kind==='register'&&!showDoc&&<aside className="register-evidence">
        <section><header><h3>Evidence & documents</h3><span>Demo records</span></header>
          <button onClick={()=>openDocument('land')}><Landmark size={20}/><div><strong>Land & parcel record</strong><small>{b.parcelId}</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>openDocument('plan')}><Layers3 size={20}/><div><strong>Floor plans</strong><small>G through floor {b.floors-1} · metre-based</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>openDocument('lease',unit)}><FileText size={20}/><div><strong>Occupancy record</strong><small>Selected unit {unit.number}</small></div><ArrowUpRight size={13}/></button>
          <button onClick={()=>downloadDocument('aerial',b)}><Map size={20}/><div><strong>District overview</strong><small>Download the full-area PDF</small></div><Download size={13}/></button>
        </section>
        <section><header><h3>Issues & discrepancies</h3><span>{findings.length} findings</span></header>{findings.length?findings.map(f=><div className="register-issue" key={f.id}><div><strong>{f.title}</strong><b>{f.value} {f.unit}</b></div><p>{f.description}</p></div>):<p className="register-empty-findings">No geometry findings for this demo footprint.</p>}</section>
        <section><header><h3>Fixture provenance</h3></header><div className="register-history"><p><i/>Land record fixture<span>{b.registeredOn}</span></p><p><i/>Occupancy period begins<span>2026-04-01</span></p><p><i/>Geometry checks<span>Computed in this session</span></p></div><p className="ins-note">These are synthetic record dates, not a real approval or ownership history.</p></section>
      </aside>}</div>}
    </div>
  </section></div>;
}
