import { Component, Suspense, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { ErrorInfo, ReactNode } from 'react';
import { Search, MapPin, ChevronRight, Layers3, Building2, TriangleAlert, Download, ShieldCheck, ChevronLeft, PanelLeftClose, PanelLeftOpen, SlidersHorizontal, Trees, Route, Droplets, Zap, Cable, Tag, Box, Focus, Maximize, Plus, Minus, ArrowUpRight, FileText, X, HelpCircle, Check, Database, Map, ChevronDown, Scan, Eye, Rotate3D, Crosshair, Info } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import CityScene from './scene/CityScene';
import Inspector from './components/Inspector';
import RecordModal from './components/RecordModal';
import { AerialMap } from './components/Visuals';
import { district, allFindings, computeFindings, getBuilding, exportGeoJSON } from './data/district';
import { downloadDocument, saveJSON } from './data/documents';
import type { Building, CameraCommand, InspectorTab, Layers, ModalKind, RecordContext } from './types';
import { mapScale } from './data/mapScale';
import DialogSection from './components/DialogSection';
import UtilitySection from './components/UtilitySection';


const defaults:Layers={buildings:true,parcels:true,roads:true,greenery:true,water:true,sewer:false,electric:false,findings:true,labels:true};
const layerConfig:{key:keyof Layers;label:string;Icon:LucideIcon;tone:string}[]=[{key:'buildings',label:'Buildings',Icon:Building2,tone:'blue'},{key:'parcels',label:'Parcels (ULPIN)',Icon:Scan,tone:'blue'},{key:'roads',label:'Roads & streets',Icon:Route,tone:'grey'},{key:'greenery',label:'Public land & trees',Icon:Trees,tone:'green'},{key:'water',label:'Water pipeline',Icon:Droplets,tone:'cyan'},{key:'sewer',label:'Sewer network',Icon:Cable,tone:'gold'},{key:'electric',label:'Electric cables',Icon:Zap,tone:'purple'},{key:'findings',label:'Findings / conflicts',Icon:MapPin,tone:'red'}];
class SceneBoundary extends Component<{children:ReactNode},{error:string|null}>{state={error:null as string|null};static getDerivedStateFromError(e:Error){return {error:e.message};}componentDidCatch(e:Error,i:ErrorInfo){console.error('3D scene failed',e,i);}render(){return this.state.error?<div className="scene-failure"><Box size={34}/><h2>3D view could not start</h2><p>{this.state.error}</p><p>Use a browser with WebGL 2 and hardware acceleration enabled.</p><button onClick={()=>location.reload()}>Reload scene</button></div>:this.props.children;}}

export default function App(){
  const [selectedId,setSelectedId]=useState<string|null>(district.defaultBuildingId),[layers,setLayers]=useState<Layers>(defaults),[leftTab,setLeftTab]=useState<'layers'|'properties'|'findings'>('layers'),[tab,setTab]=useState<InspectorTab>('overview'),[collapsed,setCollapsed]=useState(false),[mode,setMode]=useState<'2d'|'3d'>('3d'),[underground,setUnderground]=useState(false),[exploded,setExploded]=useState(false),[floor,setFloor]=useState<number|null>(null),[modal,setModal]=useState<ModalKind>(null),[query,setQuery]=useState(''),[localQuery,setLocalQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[limit,setLimit]=useState(60),[findType,setFindType]=useState('All'),[toast,setToast]=useState(''),[ready,setReady]=useState(false),[dockOpen,setDockOpen]=useState(true),[checking,setChecking]=useState(false),[presentation,setPresentation]=useState(false);
  const [command,setCommand]=useState<CameraCommand>({type:'block',nonce:0}),[camera,setCamera]=useState({x:0,z:0,zoom:6.1,heading:0}),[preview,setPreview]=useState<string|undefined>();
  const [recordContext,setRecordContext]=useState<RecordContext>({}),[mobileLayers,setMobileLayers]=useState(false),[mobileExpanded,setMobileExpanded]=useState(false);
  const openModal=useCallback((kind:ModalKind,context:RecordContext={})=>{setRecordContext(context);setModal(kind);},[]);
  const searchRef=useRef<HTMLInputElement>(null),toastTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const selected=selectedId?getBuilding(selectedId):null,recordBuilding=selected||getBuilding(district.defaultBuildingId);
  const findings=useMemo(()=>selected?computeFindings(selected):[],[selected]);
  const notify=useCallback((message:string)=>{setToast(message);if(toastTimer.current)clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),6000);},[]);
  const move=useCallback((type:CameraCommand['type'])=>setCommand(c=>({type,nonce:c.nonce+1})),[]);
  const select=useCallback((id:string)=>{setSelectedId(id);setExploded(false);setFloor(null);setTab('overview');setMobileExpanded(false);setMobileLayers(false);},[]);
  const focus=()=>move('focus');
  const selectAndFly=(id:string)=>{select(id);setCommand(c=>({type:'block',nonce:c.nonce+1}));setSearchOpen(false);};
  const changeFloor=(f:number|null)=>{setFloor(f);if(f!==null){setTab('floors');setLayers(l=>({...l,buildings:true}));}};
  const toggleExplode=()=>{setExploded(v=>!v);setFloor(null);setLayers(l=>({...l,buildings:true}));};
  const matches=(b:Building,q:string)=>`${b.ulpin} ${b.id} ${b.name} ${b.address} ${b.owner} ${b.parcelId} ${b.units.map(u=>u.occupant).join(' ')}`.toLowerCase().includes(q.toLowerCase().trim());
  const globalMatches=useMemo(()=>query.trim()?district.buildings.filter(b=>matches(b,query)).slice(0,7):[],[query]);
  const filtered=useMemo(()=>{
    const q=localQuery.trim(),base=q?district.buildings.filter(b=>matches(b,q)):district.buildings;
    const anchor=selected||getBuilding(district.defaultBuildingId);
    return [...base].sort((a,b)=>(a.id===anchor.id?-Infinity:(a.x-anchor.x)**2+(a.z-anchor.z)**2)-(b.id===anchor.id?-Infinity:(b.x-anchor.x)**2+(b.z-anchor.z)**2));
  },[localQuery,selected]);
  const filteredFindings=useMemo(()=>allFindings.filter(f=>findType==='All'||f.type===findType),[findType]);
  useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();searchRef.current?.focus();setSearchOpen(true);}if(e.key==='Escape'){setSearchOpen(false);setModal(null);}};window.addEventListener('keydown',keys);return()=>window.removeEventListener('keydown',keys);},[]);
  const handleCamera=useCallback((v:{x:number;z:number;zoom:number;heading:number})=>setCamera(old=>Math.abs(old.x-v.x)+Math.abs(old.z-v.z)+Math.abs(old.zoom-v.zoom)+Math.abs(old.heading-v.heading)<.0005?old:v),[]);
  const scale=mapScale(camera.zoom);
  const handleReady=useCallback(()=>setReady(true),[]);
  useEffect(()=>{
    if(!selectedId||!ready)return;
    const timer=setTimeout(()=>{
      const source=document.querySelector('.map-viewport canvas') as HTMLCanvasElement|null;
      const point=(window as any).__CITY_PROJECT__?.(selectedId);
      if(!source||!point)return;
      const bounds=source.getBoundingClientRect(),px=point.x-bounds.left,py=point.y-bounds.top;
      if(px<0||px>bounds.width||py<0||py>bounds.height){setPreview(undefined);return;}
      const out=document.createElement('canvas');out.width=640;out.height=350;const ctx=out.getContext('2d');if(!ctx)return;
      const w=Math.min(bounds.width,290),h=w*350/640,ratio=source.width/bounds.width;
      const sx=Math.max(0,Math.min(bounds.width-w,px-w/2)),sy=Math.max(0,Math.min(bounds.height-h,py-h/2));
      ctx.drawImage(source,sx*ratio,sy*ratio,w*ratio,h*ratio,0,0,640,350);setPreview(out.toDataURL('image/jpeg',.85));
    },1600);
    return()=>clearTimeout(timer);
  },[selectedId,command,ready,underground,exploded,floor]);
  const check=()=>{setChecking(true);setLayers(l=>({...l,findings:true}));setDockOpen(true);setTimeout(()=>{const result=district.buildings.flatMap(computeFindings);setChecking(false);notify(`Checked ${district.buildings.length} footprints: ${result.length} computed findings across ${new Set(result.map(f=>f.buildingId)).size} buildings. Demo thresholds only.`);},450);};
  const setView=(v:'2d'|'3d')=>{setMode(v);move(v);};
  const snapshot=()=>{const canvas=document.querySelector('.map-viewport canvas') as HTMLCanvasElement|null;if(!canvas){notify('Wait for the 3D map to load first.');return;}const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='DEMO-Lake-View-3D-map.png';a.click();notify('Current map image exported. The scene uses synthetic geometry.');};
  const occupied=district.buildings.reduce((n,b)=>n+b.units.filter(u=>u.tenure!=='Vacant').length,0);
  const disputed=new Set(allFindings.map(f=>f.buildingId));

  return <div className={`app ${presentation?'presentation':''}`}>
    <header className="app-header">
      <div className="brand"><div>3D ULPIN<span className="brand-edition">CITY STUDIO</span></div><p>People <b>·</b> Parcels <b>·</b> Connected places</p></div>
      <div className="global-search"><Search size={17}/><input ref={searchRef} aria-label="Search ULPIN, property or owner" placeholder="Search ULPIN / property / owner" value={query} onChange={e=>{setQuery(e.target.value);setSearchOpen(true);}} onFocus={()=>setSearchOpen(true)} onKeyDown={e=>{if(e.key==='Enter'&&globalMatches[0])selectAndFly(globalMatches[0].id);}}/><kbd>⌘ K</kbd>{searchOpen&&query.trim()&&<div className="search-results">{globalMatches.length?globalMatches.map(b=><button key={b.id} onClick={()=>selectAndFly(b.id)}><span><Building2 size={17}/></span><div><strong>{b.name}</strong><small>{b.ulpin} · {b.address}</small></div><ArrowUpRight size={15}/></button>):<p>No matching demo property.</p>}<footer>Search the complete {district.buildings.length}-building district.</footer></div>}</div>
      <div className="location-crumbs"><span><MapPin size={13}/>Lake View</span><ChevronRight size={13}/><span>District</span><em>DEMO</em></div>
      <div className="header-actions"><button onClick={()=>setModal('aerial')} title="Open district overview document"><Map size={16}/><span>Overview</span></button><button className="check-button" onClick={check} disabled={checking}><ShieldCheck size={17}/><span>{checking?'Checking…':'Check'}</span></button><button onClick={()=>setModal('export')}><Download size={16}/><span>Export</span></button></div>
      <div className="user-profile"><span className="avatar">DS</span><div><strong>Demo workspace</strong><small>Inspection mode</small></div><button className="icon-button" onClick={()=>setModal('help')} title="Map controls and help"><HelpCircle size={17}/></button></div>
    </header>
    <div className="workspace">
      {!presentation&&<aside className={`sidebar ${collapsed?'collapsed':''} ${mobileLayers?'mobile-open':''}`} aria-label="Map layers and properties">
        <button className="mobile-layer-close" aria-label="Close layers" onClick={()=>setMobileLayers(false)}><X size={18}/></button>
        {collapsed?<div className="collapsed-nav"><button title="Expand sidebar" onClick={()=>setCollapsed(false)}><PanelLeftOpen size={20}/></button><button title="Map layers" onClick={()=>{setCollapsed(false);setLeftTab('layers');}}><Layers3 size={20}/></button><button title="Properties" onClick={()=>{setCollapsed(false);setLeftTab('properties');}}><Building2 size={20}/></button><button title="Findings" onClick={()=>{setCollapsed(false);setLeftTab('findings');}}><TriangleAlert size={20}/></button></div>:<>
          <div className="sidebar-tabs">{[{id:'layers',label:'Layers',Icon:Layers3},{id:'properties',label:'Properties',Icon:Building2},{id:'findings',label:'Findings',Icon:TriangleAlert}].map(({id,label,Icon})=><button key={id} onClick={()=>setLeftTab(id as typeof leftTab)} className={leftTab===id?'active':''}><Icon size={19}/><span>{label}</span>{id==='findings'&&<i className="tab-alert"/>}</button>)}<button className="sidebar-collapse" title="Collapse sidebar" onClick={()=>setCollapsed(true)}><ChevronLeft size={14}/></button></div>
          {leftTab==='layers'&&<section className="layers-section"><div className="section-heading"><h2>Map layers</h2><button onClick={()=>{setLayers({...defaults});setUnderground(false);}}>Reset</button></div><div className="layer-rows">{layerConfig.map(({key,label,Icon,tone})=><div className="layer-row" key={key}><span className={`layer-icon ${tone}`}><Icon size={15}/></span><span>{label}</span><button className={`switch ${layers[key]?'on':''}`} aria-label={label} role="switch" aria-checked={layers[key]} onClick={()=>setLayers(l=>({...l,[key]:!l[key]}))}><i/></button></div>)}</div></section>}
          {leftTab!=='findings'?<section className="property-section"><div className="section-heading"><h2>Properties in district <span>({district.buildings.length})</span></h2>{leftTab==='properties'&&<Building2 size={16}/>}</div>{leftTab==='properties'&&<div className="property-summary"><span><strong>{district.buildings.length}</strong>buildings</span><span><strong>{occupied.toLocaleString()}</strong>occupied units</span><span><strong>{disputed.size}</strong>with findings</span></div>}<div className="local-search"><Search size={14}/><input aria-label="Search properties in district" value={localQuery} onChange={e=>{setLocalQuery(e.target.value);setLimit(60);}} placeholder="Search in district…"/>{localQuery?<button onClick={()=>setLocalQuery('')} title="Clear property search"><X size={13}/></button>:<SlidersHorizontal size={14}/>}</div><div className="property-list" data-testid="property-list">{filtered.slice(0,limit).map(b=><button key={b.id} className={`property-row ${selectedId===b.id?'selected':''}`} onClick={()=>selectAndFly(b.id)}><span className="property-icon"><Building2 size={17}/></span><span className="property-text"><strong>{b.ulpin}</strong><small>{b.address}</small></span>{disputed.has(b.id)?<span className="property-warning" title="Computed finding"><TriangleAlert size={12}/></span>:<i className="property-dot"/>}</button>)}{filtered.length===0&&<p className="empty-message">No properties match this search.</p>}{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(n=>n+60)}>Show 60 more <ChevronDown size={13}/></button>}</div><footer className="list-footer"><span>{Math.min(limit,filtered.length)} of {filtered.length} shown</span><span>Linked demo records</span></footer></section>:
          <section className="findings-section"><div className="section-heading"><h2>District findings</h2><span className="count-chip">{allFindings.length}</span></div><p className="section-caption">Computed from the actual fixture geometry.</p><div className="finding-filters">{['All','Parcel','Road','Utility'].map(t=><button className={findType===t?'active':''} key={t} onClick={()=>setFindType(t)}>{t}</button>)}</div><div className="findings-list">{filteredFindings.map(f=><button key={f.id} onClick={()=>{selectAndFly(f.buildingId);setTab(f.type==='Utility'?'utilities':'parcel');}}><span className={`finding-small-icon ${f.type==='Utility'?'blue':''}`}>{f.type==='Utility'?<Droplets size={17}/>:<TriangleAlert size={16}/>}</span><div><strong>{f.title}</strong><small>{getBuilding(f.buildingId).ulpin}</small><p>{f.value} {f.unit}<span>{f.type}</span></p></div><ChevronRight size={14}/></button>)}</div></section>}
          <div className="sidebar-status"><i/><span>Local demo dataset</span><button onClick={()=>setModal('help')} title="Dataset information"><Info size={13}/></button></div>
        </>}
      </aside>}
      {mobileLayers&&<button className="mobile-layer-scrim" aria-label="Close layer menu" onClick={()=>setMobileLayers(false)}/>}
      <main className="map-viewport" aria-label="Interactive 3D district map">
        <SceneBoundary><Suspense fallback={null}><CityScene inspectUtilities={tab==='utilities'} paused={modal!==null} onUnit={id=>openModal('register',{unitId:id,floor:selected?.units.find(u=>u.id===id)?.floor})} selected={selected} layers={layers} underground={underground} exploded={exploded} floor={floor} mode={mode} command={command} onSelect={select} onFloor={changeFloor} onCamera={handleCamera} onReady={handleReady}/></Suspense></SceneBoundary>
        {!ready&&<div className="map-loading"><span className="loading-cube"><Box size={33}/></span><h2>Building your district</h2><p>944 buildings. One connected neighbourhood.</p><div className="loading-track"><i/></div></div>}
        <button className="mobile-layers-button" aria-expanded={mobileLayers} onClick={()=>{setCollapsed(false);setMobileLayers(v=>!v);}}><Layers3 size={17}/>Layers</button>
        <div className="map-toolbar"><div className="view-switch"><button className={mode==='3d'?'active':''} onClick={()=>setView('3d')}>3D</button><button className={mode==='2d'?'active':''} onClick={()=>setView('2d')}>2D</button></div><button className={underground?'toolbar-active':''} onClick={()=>{setUnderground(v=>!v);setLayers(l=>({...l,water:true}));}}><Box size={16}/><span>Underground</span></button><button className={layers.labels?'':'muted'} onClick={()=>setLayers(l=>({...l,labels:!l.labels}))}><Tag size={15}/><span>Labels</span></button></div>
        <div className="map-fit-tools"><button onClick={()=>{move('block');}} title="Fit the selected neighbourhood"><Scan size={16}/><span>Fit block</span></button><button onClick={()=>{move('district');}} title="View all 944 buildings" data-testid="fit-district"><Maximize size={15}/><span>Fit district</span></button></div>
        <div className="district-chip"><i/>{district.buildings.length} buildings <span>·</span> 0.69 km²<span className="chip-divider"/>Synthetic district</div>
        <div className="map-controls"><button className="compass" onClick={()=>move('north')} title="Orient north"><span>N</span><i style={{transform:`rotate(${-camera.heading}rad)`}}/></button><div className="zoom-controls"><button onClick={()=>move('zoomIn')} title="Zoom in"><Plus size={19}/></button><button onClick={()=>move('zoomOut')} title="Zoom out"><Minus size={19}/></button><button onClick={focus} title="Focus selected building" disabled={!selected}><Crosshair size={18}/></button></div><button className="fullscreen-control" onClick={()=>setPresentation(v=>!v)} title={presentation?'Restore panels':'Expand map'}><Maximize size={17}/></button><button className="fullscreen-control" onClick={()=>setModal('help')} title="Map interaction help"><HelpCircle size={17}/></button></div>
        {underground&&<div className="underground-banner"><Droplets size={16}/><div><strong>Subsurface inspection</strong><span>Water −2.6 m · Sewer −3.8 m · Power −1.2 m</span></div><button onClick={()=>setUnderground(false)} title="Return to surface"><X size={15}/></button></div>}
        {selected&&tab==='utilities'&&<section className="map-section-card" aria-label="Utility section overlay"><header><strong>Section · ground to pipe</strong><button onClick={()=>setTab('overview')} aria-label="Close utility section"><X size={16}/></button></header><UtilitySection building={selected}/><p>Horizontal clearance and centre depth shown separately. Synthetic inspection geometry.</p></section>}
        <div className="minimap"><div className="minimap-image"><AerialMap selected={selectedId||undefined} onSelect={selectAndFly}/><span className="minimap-extent" style={{left:`${Math.max(4,Math.min(92,50+camera.x/8.6))}%`,top:`${Math.max(4,Math.min(92,50+camera.z/8.6))}%`,width:`${Math.max(8,Math.min(85,35/camera.zoom))}%`,height:`${Math.max(8,Math.min(85,32/camera.zoom))}%`}}/></div><button onClick={()=>{move('district');}}>District overview <ArrowUpRight size={12}/></button></div>
        {selected&&findings.length>0&&layers.findings&&floor===null&&!exploded&&<div className={`findings-dock ${!dockOpen?'compact':''}`}><div className="dock-heading"><strong><TriangleAlert size={15}/>{dockOpen?'Computed findings':'Findings'}<span>{findings.length}</span></strong><div><span>Selected building</span><button onClick={()=>setDockOpen(v=>!v)} title={dockOpen?'Collapse findings':'Expand findings'}><ChevronDown size={16} style={{transform:dockOpen?'':'rotate(180deg)'}}/></button></div></div>{dockOpen&&<div className="dock-cards">{findings.slice(0,3).map(f=><button key={f.id} onClick={()=>setTab(f.type==='Utility'?'utilities':'parcel')} className={f.type==='Utility'?'utility':''}><span className="dock-icon">{f.type==='Utility'?<Droplets size={19}/>:f.type==='Road'?<Route size={19}/>:<Scan size={19}/>}</span><div><strong>{f.type==='Parcel'?'Outside parcel':f.type==='Road'?'Road overlap':'Utility clearance'}</strong><b>{f.value} <small>{f.unit}</small></b><p>{f.type==='Parcel'?'Footprint beyond boundary':f.type==='Road'?'Intersects road corridor':'Below 2 m demo threshold'}</p></div><ChevronRight size={14}/></button>)}</div>}</div>}
        {selected&&(exploded||floor!==null)&&<div className="floor-toolbar"><span><Layers3 size={16}/>{exploded?'Exploded floors':'Floor cutaway'}</span><button className={floor===null?'active':''} onClick={()=>setFloor(null)}>All</button>{Array.from({length:selected.floors},(_,f)=><button className={floor===f?'active':''} key={f} onClick={()=>changeFloor(f)}>{f===0?'G':f}</button>)}<button title="Toggle exploded floors" className={exploded?'active':''} onClick={toggleExplode}><Layers3 size={16}/></button><button onClick={()=>{setFloor(null);setExploded(false);move('block');}} title="Return to full building"><X size={16}/></button></div>}
        <div className="map-bottom-bar"><div className="scale"><span data-metres={scale.metres} style={{width:`${scale.pixels}px`}}/><small>{scale.label}</small></div><p>Local E {camera.x.toFixed(1)} <span>·</span> N {(-camera.z).toFixed(1)} <b>|</b> Synthetic data <b>|</b> {mode==='3d'?'3D scene':'Orthographic plan'}</p></div>
        {!selected&&<div className="selection-hint"><Building2 size={17}/>Select a building to inspect its parcel, floors and records.</div>}
      </main>
      {selected&&!presentation&&<Inspector building={selected} findings={findings} tab={tab} onTab={setTab} onClose={()=>{setSelectedId(null);setFloor(null);setExploded(false);}} onFocus={focus} onModal={openModal} onFloor={changeFloor} onExplode={toggleExplode} exploded={exploded} floor={floor} preview={preview} mobileExpanded={mobileExpanded} onToggleMobile={()=>setMobileExpanded(v=>!v)}/>}
    </div>
    {toast&&<div className="toast" role="status"><Check size={17}/><span>{toast}</span><button title="Dismiss notification" onClick={()=>setToast('')}><X size={15}/></button></div>}
    {modal&&modal!=='export'&&<RecordModal key={`${modal}-${recordContext.unitId||''}-${recordContext.doc||''}`} context={recordContext} preview={preview} kind={modal} building={recordBuilding} findings={findings} onClose={()=>setModal(null)} onFloor={f=>{changeFloor(f);focus();}}/>}
    {modal==='export'&&<div className="rec-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><DialogSection onClose={()=>setModal(null)} labelledBy="export-title" className="export-dialog"><header><span className="export-icon"><Database size={25}/></span><button className="icon-button" onClick={()=>setModal(null)} aria-label="Close export dialog"><X size={20}/></button></header><span className="ins-eyebrow">LOCAL, SELF-CONTAINED DATASET</span><h2 id="export-title">Take the district with you.</h2><p>Export the same records and geometry used by the map. Every dataset and document is clearly marked as synthetic.</p><div className="export-stats"><span><strong>{district.buildings.length}</strong>buildings & parcels</span><span><strong>{district.buildings.reduce((s,b)=>s+b.units.length,0).toLocaleString()}</strong>unit records</span><span><strong>{district.utilities.length}</strong>utility segments</span></div><div className="export-options"><button onClick={()=>{saveJSON(exportGeoJSON(),'DEMO-lake-view-parcels.geojson');notify('944 synthetic parcels exported as GeoJSON.');}}><Map size={20}/><div><strong>2D parcel GeoJSON</strong><small>14-digit demo IDs · approximate WGS84 placement</small></div><Download size={16}/></button><button onClick={()=>{saveJSON({...district,synthetic:true,findings:allFindings},'DEMO-complete-district.json');notify('Complete linked district dataset exported.');}}><Database size={20}/><div><strong>Complete linked dataset</strong><small>Buildings, floors, residents, roads, utilities & findings</small></div><Download size={16}/></button><button onClick={()=>downloadDocument('aerial',recordBuilding)}><FileText size={20}/><div><strong>District overview PDF</strong><small>Entire area, north arrow context & legend</small></div><Download size={16}/></button><button onClick={snapshot}><Box size={20}/><div><strong>Current map as PNG</strong><small>Capture the current 3D or 2D camera view</small></div><Download size={16}/></button></div><div className="export-note"><Info size={16}/><p>Local dimensions are synthetic metres. GeoJSON uses an approximate demonstration origin near Delhi, not a surveyed location. No official land records or real personal data are included.</p></div></DialogSection></div>}
  </div>;
}
