const fs=require('fs');let s=fs.readFileSync('src/components/RecordModal.tsx','utf8');function r(a,b){if(!s.includes(a))throw Error(a);s=s.replace(a,b);}
r("import type { Building, Finding, ModalKind, Unit } from '../types';","import type { Building, Finding, ModalKind, Unit, RecordContext } from '../types';\nimport { useDialog } from './useDialog';");
r('type Props={kind:ModalKind;building:Building;findings:Finding[];onClose:()=>void;onFloor:(f:number|null)=>void};','type Props={kind:ModalKind;building:Building;findings:Finding[];onClose:()=>void;onFloor:(f:number|null)=>void;context?:RecordContext;preview?:string};');
r('export default function RecordModal({kind,building:b,findings,onClose,onFloor}:Props){','export default function RecordModal({kind,building:b,findings,onClose,onFloor,context={},preview}:Props){');
r("const [docType,setDocType]=useState<DocumentType>('land'),[unit,setUnit]=useState<Unit>(b.units.find(u=>u.tenure==='Rented')||b.units[0]),[floor,setFloor]=useState(0),[showDoc,setShowDoc]=useState(kind==='documents');", "const initialUnit=b.units.find(u=>u.id===context.unitId)||b.units.find(u=>u.floor===context.floor)||b.units.find(u=>u.tenure==='Rented')||b.units[0];\n  const [docType,setDocType]=useState<DocumentType>(context.doc||(context.unitId?'lease':'land')),[unit,setUnit]=useState<Unit>(initialUnit),[floor,setFloor]=useState(context.floor??initialUnit.floor),[showDoc,setShowDoc]=useState(kind==='documents'||Boolean(context.unitId));\n  const dialogRef=useDialog(onClose);");
r("  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[onClose]);",'');
r('<section role="dialog" aria-modal="true"','<section ref={dialogRef} tabIndex={-1} role="dialog" aria-modal="true"');
r('<aside className="rec-property"><BuildingPreview b={b}/>','<aside className="rec-property">{preview?<img className="building-preview" src={preview} alt={b.name}/>:<BuildingPreview b={b}/>}');
r('<div className="rec-unit-card" key={u.id}>','<div className={`rec-unit-card ${u.id===unit.id?\'selected-unit\':\'\'}`} data-unit-id={u.id} key={u.id}>');
r('<FloorPlan b={b} floor={floor}/>','<FloorPlan b={b} floor={floor} selectedUnit={unit.id} onUnit={id=>{const found=b.units.find(u=>u.id===id);if(found){setUnit(found);setFloor(found.floor);setDocType(\'lease\');}}}/>');
fs.writeFileSync('src/components/RecordModal.tsx',s);
